# Generated by Django 3.1.6 on 2021-02-08 21:32

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210208_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scp',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='tales',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
    ]
