# Generated by Django 3.1.6 on 2021-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210208_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tales',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
