# Generated by Django 3.1.6 on 2021-02-11 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210210_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='scp',
            name='saved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='savedscps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tales',
            name='saved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='savedtales', to=settings.AUTH_USER_MODEL),
        ),
    ]
